// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { OperatorApproval } from "./tables/OperatorApproval.sol";
import { Ownership } from "./tables/Ownership.sol";
import { TokenApproval } from "./tables/TokenApproval.sol";
import { Balance } from "./tables/Balance.sol";
